In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# 12(a)

For them to be equal,
summation of xi^2 and summation of yi^2 need to be equal,
i.e,
np.dot(x, x)==np.dot(y, y)

# 12(b)

In [17]:
# for them not need to be equal, we have to not satisfy the above condition
# taking rng
rng = np.random.default_rng(69)
x = rng.random(100)
y = 10*x + rng.normal(size=100)

In [18]:
x, y

(array([0.58037238, 0.52685204, 0.86496166, 0.73476041, 0.47658484,
        0.81669623, 0.54463478, 0.43741576, 0.0084511 , 0.67847371,
        0.78631358, 0.70592772, 0.96210933, 0.72168282, 0.01143179,
        0.92750361, 0.82252916, 0.68171474, 0.73382701, 0.06819783,
        0.01821376, 0.53768628, 0.90185421, 0.72114621, 0.89514852,
        0.29345189, 0.46985248, 0.28662978, 0.5489505 , 0.86394085,
        0.52791247, 0.76286433, 0.91883206, 0.4483622 , 0.51480899,
        0.54968553, 0.48158167, 0.84639263, 0.52116532, 0.224657  ,
        0.48031686, 0.1153437 , 0.54378739, 0.51794282, 0.84453545,
        0.29325741, 0.82051979, 0.16583378, 0.44251419, 0.83049518,
        0.33640324, 0.44591461, 0.74002415, 0.69608549, 0.07092868,
        0.13875422, 0.12906965, 0.58048624, 0.50270434, 0.91205114,
        0.19838823, 0.85824718, 0.83746129, 0.6199761 , 0.3280464 ,
        0.65095333, 0.75710517, 0.50766599, 0.11475895, 0.63859254,
        0.7352097 , 0.2668269 , 0.54721098, 0.99

In [19]:
result1 = sm.OLS(y, x).fit()
result1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.968
Model:                            OLS   Adj. R-squared (uncentered):              0.968
Method:                 Least Squares   F-statistic:                              3004.
Date:                Mon, 09 Oct 2023   Prob (F-statistic):                    7.09e-76
Time:                        19:07:27   Log-Likelihood:                         -147.53
No. Observations:                 100   AIC:                                      297.1
Df Residuals:                      99   BIC:                                      299.7
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             9.7811      0.178     54.809      0.000       9.427      10.135
==============================================================================
Omnibus:                        3.215   Durbin-Watson:                   2.108
Prob(Omnibus):                  0.200   Jarque-Bera (JB):                2.493
Skew:                          -0.248   Prob(JB):                        0.287
Kurtosis:                       2.406   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
result1_new = sm.OLS(x, y).fit()
result1_new.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.968
Model:                            OLS   Adj. R-squared (uncentered):              0.968
Method:                 Least Squares   F-statistic:                              3004.
Date:                Mon, 09 Oct 2023   Prob (F-statistic):                    7.09e-76
Time:                        19:07:40   Log-Likelihood:                          82.132
No. Observations:                 100   AIC:                                     -162.3
Df Residuals:                      99   BIC:                                     -159.7
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0990      0.002     54.809      0.000       0.095       0.103
==============================================================================
Omnibus:                        3.885   Durbin-Watson:                   2.048
Prob(Omnibus):                  0.143   Jarque-Bera (JB):                2.796
Skew:                           0.255   Prob(JB):                        0.247
Kurtosis:                       2.360   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### Their coefficient estimates are substantially different, i.e 9.7811 and 0.0990.

# 12(c)

In [12]:
# we have to satify, np.dot(x, x) == np.dot(y, y)
x = np.random.permutation(np.arange(100))
y = np.random.permutation(np.arange(100))

In [13]:
x

array([29, 61, 60, 59, 22, 46, 45, 94, 41,  5, 90,  2, 14, 28,  6,  4, 65,
       50, 56, 78, 19, 77, 48, 23, 52,  8, 63, 31, 98, 97, 57,  7, 32, 72,
       86, 80,  0, 11, 21, 43, 16,  3, 75, 92, 44, 76, 20, 42,  9, 40, 39,
       87, 33, 58, 17, 38, 66, 88, 25, 70, 64, 49, 69, 15, 71, 27, 79, 62,
       96, 74, 54, 10, 47, 91, 37, 26, 82, 36, 55, 95, 12, 68, 99, 34, 18,
       30, 35, 24, 67, 13, 73,  1, 93, 83, 51, 53, 85, 84, 89, 81])

In [14]:
y

array([ 2, 39, 22, 49, 30, 54, 68, 32, 18, 79, 84, 85, 35, 26, 69,  3, 48,
       28,  6, 15, 42, 63, 16,  9, 97, 94, 86, 59, 81, 87, 53, 72, 34, 45,
        8, 27, 77, 56, 90, 31, 92,  5, 14,  7, 88, 43, 73, 40, 47, 13, 62,
       61, 89, 19, 36, 74, 50, 51, 64, 37, 21, 83, 70, 96, 65, 58, 41, 11,
       76, 99, 91, 24, 55, 82, 71, 67,  4, 17, 44, 20, 25, 78, 38, 60, 23,
       66, 95, 46, 29, 52, 80, 98,  1, 33, 10, 12, 93,  0, 75, 57])

In [15]:
result2 = sm.OLS(y, x).fit()
result2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.515
Model:                            OLS   Adj. R-squared (uncentered):              0.511
Method:                 Least Squares   F-statistic:                              105.3
Date:                Mon, 09 Oct 2023   Prob (F-statistic):                    2.93e-17
Time:                        19:01:52   Log-Likelihood:                         -510.50
No. Observations:                 100   AIC:                                      1023.
Df Residuals:                      99   BIC:                                      1026.
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.7180      0.070     10.263      0.000       0.579       0.857
==============================================================================
Omnibus:                        2.051   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.359   Jarque-Bera (JB):                1.491
Skew:                           0.064   Prob(JB):                        0.475
Kurtosis:                       2.416   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
result2_new = sm.OLS(x, y).fit()
result2_new.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.515
Model:                            OLS   Adj. R-squared (uncentered):              0.511
Method:                 Least Squares   F-statistic:                              105.3
Date:                Mon, 09 Oct 2023   Prob (F-statistic):                    2.93e-17
Time:                        19:02:26   Log-Likelihood:                         -510.50
No. Observations:                 100   AIC:                                      1023.
Df Residuals:                      99   BIC:                                      1026.
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.7180      0.070     10.263      0.000       0.579       0.857
==============================================================================
Omnibus:                        2.478   Durbin-Watson:                   1.690
Prob(Omnibus):                  0.290   Jarque-Bera (JB):                1.705
Skew:                          -0.091   Prob(JB):                        0.426
Kurtosis:                       2.387   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### Their coefficient estimates are same.